name: Export Spotify Data

on:
  schedule:
    - cron: '30 18 * * 5'  # Tous les vendredis à 19h30 UTC+1
  workflow_dispatch:  # Permet d'exécuter manuellement

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: pip install spotipy

      - name: Exécuter le script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
        run: python spotify_export.py

      - name: Sauvegarder les résultats
        uses: actions/upload-artifact@v3
        with:
          name: spotify_data
          path: spotify_data.json
