name: Export Spotify Liked Tracks

on:
  schedule:
    - cron: '0 0 * * *'  # Exécute tous les jours à minuit UTC
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Cloner le dépôt
        uses: actions/checkout@v4

      - name: 🐍 Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Installer les dépendances
        run: pip install spotipy python-dotenv pandas

      - name: 🔑 Configurer les variables d'environnement
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
        run: echo "Secrets chargés avec succès"

      - name: 🚀 Exécuter le script
        run: python spotify_export.py

      - name: 📤 Sauvegarder le fichier exporté
        uses: actions/upload-artifact@v4
        with:
          name: spotify_liked_tracks
          path: spotify_liked_tracks.csv
